name: safe_device
description: With the Flutter safe_device package, you can easily implement security steps such as Jailbroken, root, emulator and fake location detection.
version: 1.1.4
homepage: https://github.com/ufukhawk/safe_device

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xamdesign.safe_device
        pluginClass: SafeDevicePlugin
      ios:
        pluginClass: SafeDevicePlugin
